rocommunity public poller-2
agentaddress UDP6:161,UDP:161
syscontact pn@some.net
syslocation Ada [45.111111,20.111111]
sysName poller-2.docker.soada
sysDescr Linux NMS-POLLER
extend distro /opt/librenms/.docker/prgs/agents/distro
extend hardware "/bin/cat /sys/devices/virtual/dmi/id/product_name"
extend manufacturer "/bin/cat /sys/devices/virtual/dmi/id/sys_vendor"
